version: '3.8'

services:
  backend:
    image: 850960379966.dkr.ecr.us-east-1.amazonaws.com/interview-backend:latest
    container_name: interview-backend
    ports:
      - "8000:8000"
    volumes:
      - ./interview_app.db:/app/interview_app.db
    environment:
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}


  frontend:
    image: 850960379966.dkr.ecr.us-east-1.amazonaws.com/interview-frontend:latest
    container_name: interview-frontend
    ports:
      - "8501:8501"
    environment:
      API_URL: http://backend:8000
    depends_on:
      - backend